// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/_dev/db-inspect': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_dev/db-inspect.get').default>>>>
    }
    '/api/account/subscriptions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/account/subscriptions.get').default>>>>
    }
    '/api/auth/call-verify/complete/:token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/call-verify/complete/[token].get').default>>>>
    }
    '/api/auth/call-verify/request': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/call-verify/request.post').default>>>>
    }
    '/api/auth/call-verify/status/:token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/call-verify/status/[token].get').default>>>>
    }
    '/api/auth/contract': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/contract.post').default>>>>
    }
    '/api/auth/telegram-deeplink/complete/:token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/telegram-deeplink/complete/[token].get').default>>>>
    }
    '/api/auth/telegram-deeplink/request': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/telegram-deeplink/request.post').default>>>>
    }
    '/api/auth/telegram-deeplink/status/:token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/telegram-deeplink/status/[token].get').default>>>>
    }
    '/api/chat/bot/respond': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/bot/respond.post').default>>>>
    }
    '/api/chat/close': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/close.post').default>>>>
    }
    '/api/chat/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/messages.get').default>>>>
    }
    '/api/chat/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/send.post').default>>>>
    }
    '/api/chat/session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/session.post').default>>>>
    }
    '/api/chat/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/upload.post').default>>>>
    }
    '/api/community/messages/:id/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/messages/[id]/delete.post').default>>>>
    }
    '/api/community/messages/:id/edit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/messages/[id]/edit.post').default>>>>
    }
    '/api/community/messages/:id/pin': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/messages/[id]/pin.post').default>>>>
    }
    '/api/community/messages/:id/report': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/messages/[id]/report.post').default>>>>
    }
    '/api/community/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/messages/index.get').default>>>>
    }
    '/api/community/messages/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/messages/send.post').default>>>>
    }
    '/api/community/moderation/moderators': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/moderation/moderators.get').default>>>>
    }
    '/api/community/moderation/mute': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/moderation/mute.post').default>>>>
    }
    '/api/community/moderation/set-role': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/moderation/set-role.post').default>>>>
    }
    '/api/community/moderation/unmute': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/moderation/unmute.post').default>>>>
    }
    '/api/community/rooms/:id/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/rooms/[id]/info.get').default>>>>
    }
    '/api/community/rooms/:id/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/rooms/[id]/join.post').default>>>>
    }
    '/api/community/rooms/:id/my-role': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/rooms/[id]/my-role.get').default>>>>
    }
    '/api/community/rooms/:id/online': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/rooms/[id]/online.get').default>>>>
    }
    '/api/community/rooms': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/rooms/index.get').default>>>>
    }
    '/api/community/rooms/mark-read': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/rooms/mark-read.post').default>>>>
    }
    '/api/community/upload/image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/community/upload/image.post').default>>>>
    }
    '/api/invoices': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/index.get').default>>>>
    }
    '/api/invoices/unpaid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/unpaid.get').default>>>>
    }
    '/api/news/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/[id].get').default>>>>
    }
    '/api/news': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/index.get').default>>>>
    }
    '/api/services': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/services/index.get').default>>>>
    }
    '/api/speedtest/download': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/speedtest/download.get').default>>>>
    }
    '/api/speedtest/getip': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/speedtest/getip.get').default>>>>
    }
    '/api/speedtest/ping': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/speedtest/ping.get').default>>>>
    }
    '/api/speedtest/telemetry': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/speedtest/telemetry.post').default>>>>
    }
    '/api/speedtest/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/speedtest/upload.post').default>>>>
    }
    '/api/support/faq': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/support/faq.get').default>>>>
    }
    '/api/support/tickets/:id/close': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/support/tickets/[id]/close.post').default>>>>
    }
    '/api/support/tickets/:id/comment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/support/tickets/[id]/comment.post').default>>>>
    }
    '/api/support/tickets/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/support/tickets/[id]/index.get').default>>>>
    }
    '/api/support/tickets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/support/tickets/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/support/tickets/index.post').default>>>>
    }
    '/api/telegram/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/telegram/webhook.post').default>>>>
    }
    '/api/user/avatar': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/avatar.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/avatar.post').default>>>>
    }
    '/api/user/presence': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/presence.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/presence.post').default>>>>
    }
    '/api/user/profile/nickname': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/profile/nickname.patch').default>>>>
    }
    '/api/user/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/update.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.2.2_db0@0.3.4_ioredis@5.9.2_magicast@0.5.1_nuxt@4.2.2_@parcel+watc_f05c0620bbd6c991cd0ebdf430263a13/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.1_vite@7.3.1_@types+node@25.0.10_jiti@2.6.1_terser@5.46.0_yaml@2.8.2__vue@3.5.27/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}