// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_vue@3.5.27_/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@2.0.3/node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@2.0.3/node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_vue@3.5.27_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7.3.1_@types+node@25.0.10_jiti@2.6.1_terser@5.46.0_yaml@2.8.2__vue@3.5.27/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7.3.1_@types+node@25.0.10_jiti@2.6.1_terser@5.46.0_yaml@2.8.2__vue@3.5.27/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/pinia-plugin-persistedstate@4.7.1_@nuxt+kit@4.2.2_magicast@0.5.1__@pinia+nuxt@0.11.3_ma_af7270f1473f9a8f11ff350f4bf9deb4/node_modules/pinia-plugin-persistedstate/dist/nuxt/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.1_vite@7.3.1_@types+node@25.0.10_jiti@2.6.1_terser@5.46.0_yaml@2.8.2__vue@3.5.27/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'supabase' | 'supabase' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'pinia-plugin-persistedstate' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
