// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 19.02.2026, 15:22:21
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/anna/Рабочий стол/pg19V/pg19client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/anna/Рабочий стол/pg19V/pg19client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/anna/Рабочий стол/pg19V/pg19client/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/anna/Рабочий стол/pg19V/pg19client/app/plugins/**/*.{js,ts,mjs}","/home/anna/Рабочий стол/pg19V/pg19client/app/composables/**/*.{js,ts,mjs}","/home/anna/Рабочий стол/pg19V/pg19client/app/utils/**/*.{js,ts,mjs}","/home/anna/Рабочий стол/pg19V/pg19client/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/anna/Рабочий стол/pg19V/pg19client/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/anna/Рабочий стол/pg19V/pg19client/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/anna/Рабочий стол/pg19V/pg19client/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;