export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta } from '../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.4_@types+node@25.0.10_@vue+compiler-sfc@3.5.27_cac@6.7.1_7e158e092e44ef7f48c6306effaf518f/node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useAchievementsApi } from '../app/composables/useAchievementsApi';
export { useAuthInit } from '../app/composables/useAuthInit';
export { useCallVerification } from '../app/composables/useCallVerification';
export { useChat } from '../app/composables/useChat';
export { useCommunityChat } from '../app/composables/useCommunityChat';
export { useFaq } from '../app/composables/useFaq';
export { formatRelativeDate, formatDateTime, formatDate, formatDateShort, formatKopeks, formatFileSize, truncateText, formatContractNumber, useFormatters } from '../app/composables/useFormatters';
export { mockInvoiceDetails, useInvoiceServices, InvoiceService, InvoiceAddress, InvoiceDetails } from '../app/composables/useInvoiceServices';
export { useInvoices } from '../app/composables/useInvoices';
export { useNews } from '../app/composables/useNews';
export { useNotificationsApi } from '../app/composables/useNotificationsApi';
export { usePresenceHeartbeat } from '../app/composables/usePresenceHeartbeat';
export { useReferralApi } from '../app/composables/useReferralApi';
export { useServices } from '../app/composables/useServices';
export { useSessionsApi } from '../app/composables/useSessionsApi';
export { useTelegramDeeplink } from '../app/composables/useTelegramDeeplink';
export { useTickets } from '../app/composables/useTickets';
export { useUserApi } from '../app/composables/useUserApi';
export { useAccountStore } from '../app/stores/account';
export { useAchievementsStore } from '../app/stores/achievements';
export { useChatStore } from '../app/stores/chat';
export { useNotificationsStore } from '../app/stores/notifications';
export { useReferralStore } from '../app/stores/referral';
export { useSessionsStore } from '../app/stores/sessions';
export { useUserStore } from '../app/stores/user';
export { useSupabaseClient } from '../node_modules/.pnpm/@nuxtjs+supabase@2.0.3/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseClient';
export { useSupabaseCookieRedirect } from '../node_modules/.pnpm/@nuxtjs+supabase@2.0.3/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseCookieRedirect';
export { useSupabaseSession } from '../node_modules/.pnpm/@nuxtjs+supabase@2.0.3/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseSession';
export { useSupabaseUser } from '../node_modules/.pnpm/@nuxtjs+supabase@2.0.3/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseUser';
export { useColorMode } from '../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/composables';
export { defineStore, acceptHMRUpdate, usePinia, storeToRefs } from '../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_vue@3.5.27_/node_modules/@pinia/nuxt/dist/runtime/composables';
export { storages as piniaPluginPersistedstate } from '../node_modules/.pnpm/pinia-plugin-persistedstate@4.7.1_@nuxt+kit@4.2.2_magicast@0.5.1__@pinia+nuxt@0.11.3_ma_af7270f1473f9a8f11ff350f4bf9deb4/node_modules/pinia-plugin-persistedstate/dist/nuxt/runtime/storages';
export { useNuxtDevTools } from '../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7.3.1_@types+node@25.0.10_jiti@2.6.1_terser@5.46.0_yaml@2.8.2__vue@3.5.27/node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';